### PR TITLE
Dark mode + Improvements

### PR DESCRIPTION
**Pull request by Escartem**
Added a dark mode for the interface : 

image

Along with a new scrollbar : 

image

I've also updated package.json because concurrently was missing (Pretty sure I've fixed this in #3 too 🤔 ). And I disabled user select.

Stuff to do : 
- the arrow of the menu for the voice selector is not visible in dark mode
- a switch could be added to toggle dark mode

### CODE REVIEW

**Comment by SietseT** [comment]
Hi @Escartem, sorry for not getting back to you earlier! I like the dark-mode design, but it's missing two things that you've already noticed. Would it be possible to fix those as well? Would love to merge this PR, since it also fixes the resizing issue.

**Comment by Escartem** [comment]
Hi @SietseT, I will try to fix those issues when I have some time so this can be merged 👍

**Comment by Escartem** [comment]
The dark theme should now be ready 👍 
I have fixed the arrow, added a button to switch the theme, and also a nice transition when switching.
All the JS and CSS was added in the index.html but you probably want to move that to another file, the only last thing that could be added is a memorization of the theme so when we reopen the app it keeps it but I don't have enough experience to do it :c

**Comment by SietseT** [comment]
Thanks! I'll merge the PR, but as you said move the JS, CSS etc. to a React component so it's consistent in the entire app. Also it will be easier to store the user's selected theme.

**Pull request merged**
